fix: shared package for nodenext module resolution
Running tests using vitest in the server-nestjs package seems to break module resolution because of nodenext module resolution.

```
Error: Failed to resolve entry for package "@cpn-console/shared". The package may have incorrect main/module/exports specified in its package.json.
```

Signed-off-by: William Phetsinorath <william.phetsinorath-open@interieur.gouv.fr>